{
 "title": "Troubleshooting Kubernetes (simple and fast view)",
 "description": "Simple dashboard that allows you to view basic information about deployments, pods, logs, and \"Pod reason error\"",
 "tags": [
  "troubleshooting",
  "trouble",
  "pod",
  "pods",
  "kubectl",
  "fast view",
  "sre",
  "simple"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_created,node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(kube_namespace_labels)"
    }
   },
   {
    "name": "container_error",
    "label": "container_error",
    "query": {
     "query": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\"}"
    }
   },
   {
    "name": "duration",
    "label": "duration",
    "query": "5m,10m,30m,1h,2h,6h,12h,1d,2d,5d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Namespace $namespace details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total nodes",
   "type": "stat",
   "description": "Similar to:   kubectl get nodes\n-\n\nFor more details use dashboards:\n- \n- Default / Nodes",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "description": "Similar to:  kubectl get namespace\n-",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "title": "Total  pods",
   "type": "stat",
   "description": "Similar to:   kubectl get pod \n-",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{namespace=\"$namespace\",container=\"POD\"}))"
    }
   ]
  },
  {
   "title": "Ready pods",
   "type": "stat",
   "description": "Similar to:   kubectl get pods |grep Running\n-",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "stat",
   "description": "Similar to:   kubectl get pods |grep -v Running",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated{namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Age",
   "type": "stat",
   "description": "Similar to:   kubectl get nodes  (filter by Age)\n-",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - kube_service_created{namespace=\"default\",service=\"kubernetes\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "description": "similar to:   kubectl get deployments\n-",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{namespace=\"$namespace\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "ConfigMaps",
   "type": "stat",
   "description": "Similar to:   kubectl get configmap\n-",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_configmap_created{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "stat",
   "description": "Similar to:   kubectl get ingress\n-",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_ingress_created{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "stat",
   "description": "Similar to:   kubectl get secrets\n-",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_secret_created{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "stat",
   "description": "Show Persisten Volumes\n-\n\nFor more details use dashboard\n-\n- Default / kubernetes / Persistent Volumes",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVCs Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Pending\",namespace=\"$namespace\"} != 0)"
    }
   ]
  },
  {
   "title": "PVCs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Failed\",namespace=\"$namespace\"} != 0) "
    }
   ]
  },
  {
   "title": "pods running in $namespace",
   "type": "table",
   "description": "Similar to run:   kubectl get pod \n-\n-\n\nFor more detail use dashboards:  \n- \n- Default /  Kubernetes / Compute Resources / Workload\n- Default / Logs by App  \n- Default / Data and Info\n\n",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\"}"
    },
    {
     "expr": "kube_pod_info{namespace=\"$namespace\"}"
    },
    {
     "expr": "time() - kube_pod_start_time{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "POD Status waiting reason",
   "type": "table",
   "description": "The CrashLoopBackOff:\n-\n\n* Insufficient resources—lack of resources prevents the container from loading\n* Locked file—a file was already locked by another container\n* Locked database—the database is being used and locked by other pods\n* Failed reference—reference to scripts or binaries that are not present on the container\n* Setup error—an issue with the init-container setup in Kubernetes\n* Config loading error—a server cannot load the configuration file\n* Misconfigurations—a general file system misconfiguration\n* Connection issues—DNS or kube-DNS is not able to connect to a third-party service\n* Deploying failed services—an attempt to deploy services/applications that have already failed (e.g. due to a lack of access to other services)\n\nThe ImagePullBackOff:\n-----------------------------------\n\nmeans that a Pod couldn’t start because Kubernetes could not pull a container image. The ‘BackOff’ part indicates that Kubernetes will keep trying to pull the image, with an increasing back-off delay.  \n- check  if image exist\n- check if image tag is correct\n- check if you have the secret to pull image from private registry\n- check if  the value \"imagePullSecrets\" is right configured in your deployment  (use GIT repo to check it)\n\n-\n\nFor more details use dashboards:  \n-\n- Default / Logs by App\n- Default / Data and Info",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "PVCs available capacity in namespacee $namespace",
   "type": "bargauge",
   "description": "Similar to run:   kubectl get pv \n-\n\n-\n\nFor more detail use dashboard:   \n-\n- Default / Kubernetes / Persistent Volumes",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=\"$namespace\"}\n  / kubelet_volume_stats_capacity_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=\"$namespace\"}\n ",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PersistentVolumeClaim status in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(kube_persistentvolumeclaim_access_mode{namespace=\"$namespace\"})",
     "legendFormat": "{{access_mode}}::{{persistentvolumeclaim}}"
    },
    {
     "expr": "kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\",phase=\"Bound\"}",
     "legendFormat": "Bound::{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Ingress in $namespace namespace",
   "type": "table",
   "description": "Similar to run:  kubectl get ingress\n-",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_ingress_path{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Last 100  error logs from  container:  $container_error",
   "type": "logs",
   "description": "Similar to:    kubectl logs pod \n- \n-\n\nFor more info use dashboards\n-\n- Default / Logs by App\n\n",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{stream=~\"stderr\", namespace=\"$namespace\", container=\"$container_error\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}