{
 "title": "Kubernetes Ingress Nginx",
 "description": "Number of requests and bytes size by server zone and backend service",
 "tags": [
  "k8s",
  "kubernetes",
  "ingress",
  "nginx",
  "stats"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "ingressName", "query": "nginx_requests_total" }
  ]
 },
 "panels": [
  {
   "title": "Requests / min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_requests_total{server_zone!=\"*\", release=\"$ingressName\"}[5m]) * 60",
     "legendFormat": "{{release}} - {{server_zone}}"
    }
   ]
  },
  {
   "title": "Bytes transferred / min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "- irate(nginx_bytes_total{direction=\"in\",server_zone!=\"*\",release=\"$ingressName\"}[5m]) * 60",
     "legendFormat": "{{release}} - {{server_zone}} - {{direction}}"
    },
    {
     "expr": "irate(nginx_bytes_total{direction=\"out\",server_zone!=\"*\",release=\"$ingressName\"}[5m]) * 60",
     "legendFormat": "{{release}} - {{server_zone}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Backend requests / min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_upstream_requests_total{release=\"$ingressName\"}[5m]) * 60",
     "legendFormat": "{{upstream}} - {{server}}"
    }
   ]
  },
  {
   "title": "Backend response time ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_upstream_response_msecs_avg{release=\"$ingressName\"}) by (upstream)",
     "legendFormat": "{{upstream}}"
    }
   ]
  }
 ]
}